name: 'Cypress Screenshot & Video Upload to Slack'
branding:
  icon: file
  color: blue
description: 'After running a Cypress test in a Github action, upload the screenshots and videos directly to Slack'
inputs:
  token:
    description: 'Slack token'
    required: true
  channels:
    description: 'Slack channels'
    required: true
  workdir:
    description: 'The path of the directory where Cypress stores its screenshots. Defaults to `./cypress`. No trailing slashes, please.'
    required: false
  messageText:
    description: 'Custom Slack message text'
    required: false
outputs:
  result:
    description: 'Result of video and screenshot uploads'
runs:
  using: 'node12'
  main: 'dist/index.js'
